# NOTE: Add GitHub username
default_assignee: "SnapSoftGabrielStp"

# NOTE: Anything else above medium is considered large
size_labels:
  small: 50
  medium: 200

# NOTE: Add GitHub usernames
reviewers:
  - "snapkristof"
  - "vtstanescu"
