name: PR Code Quality Checks
run-name: "${{ github.actor }} is running workflow against commit: ${{ github.sha }}"
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-code-quality-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Mise install
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8
        with:
          install: true
          cache: true

      - name: Run Go checks
        run: mise run test-all
